import { StatusBar } from 'expo-status-bar';
import * as ImagePicker from 'expo-image-picker';
import { useRouter } from 'expo-router';
import { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Alert, Image, Modal, Platform, Pressable, SafeAreaView, ScrollView, StyleSheet, Switch, Text, TextInput, View } from 'react-native';
import type { Chat, Evaluation, LearningSnapshot, MissionOrigin, MissionRecord, Phrase, PhotoMission, Scene, SceneId, Stage, Tab, Twin, VisionAnalysis } from './src/domain/types';
import { continuePracticeDialogue, evaluatePractice, inferTwinFromTurkish } from './src/services/learningEngine';
import { loadLearningSnapshot, saveLearningSnapshot } from './src/services/learningRepository';
import { createMissionFromPhoto, demoAnalysisFor } from './src/services/missionPipeline';

const C = { navy: '#092D46', teal: '#168C83', tealPale: '#DDF3EF', amber: '#F3AF3D', amberPale: '#FFF3D9', coral: '#DE6B50', coralPale: '#FFF0EB', ink: '#182632', slate: '#60707A', mist: '#F3F7F7', line: '#DCE7E7', white: '#FFFFFF' };
const SCENES: Record<SceneId, Scene> = {
  desk: { id: 'desk', icon: '⌁', title: 'Desk rescue', place: 'Çalışma masası', confidence: 92, objects: ['Laptop', 'Şarj kablosu', 'Kahve'], context: 'Çalışırken laptopun şarjı azalıyor. Kısa, net bir destek isteği hayatı kolaylaştırabilir.', mission: 'Low battery, clear ask', objective: 'Yakındaki birinden priz veya şarj desteği iste.', partner: 'Mina · coworker', opening: 'Hey! You look a little stuck. Is everything okay?', phrase: { id: 'desk', en: 'My battery is running low. Is there a plug nearby?', tr: 'Şarjım bitmek üzere. Yakında priz var mı?', context: 'Ofis / çalışma', used: false }, color: '#1C6970' },
  jury: { id: 'jury', icon: '◉', title: 'The presentation problem', place: 'Jüri masası', confidence: 96, objects: ['Mikrofon', 'Su şişesi', 'Laptop', 'Not defteri'], context: 'Bir sunum başlamak üzere. Görünen nesneler, mikrofonla ilgili bir sorun ve kısa hazırlık ihtiyacını işaret ediyor.', mission: 'The presentation problem', objective: 'Organizatörden mikrofon konusunda yardım ve su iste.', partner: 'Emre · event organizer', opening: 'Hi! We are about to start. Do you need anything before your presentation?', phrase: { id: 'jury', en: 'I think the mic is not working. Could you give me a hand?', tr: 'Sanırım mikrofon çalışmıyor. Yardım edebilir misiniz?', context: 'Sunum', used: true }, color: '#304D7C' },
  cafe: { id: 'cafe', icon: '☕', title: 'Coffee, but make it work', place: 'Kafe', confidence: 89, objects: ['Kahve bardağı', 'Laptop', 'Masa'], context: 'Kahven soğumuş; çalışmaya devam etmek için kısa ve nazik bir isteğe ihtiyacın var.', mission: 'A warmer coffee break', objective: 'Baristadan sıcak su ve masaya yakın bir priz iste.', partner: 'Mina · barista', opening: 'Hello! How is your coffee? Can I help with anything?', phrase: { id: 'cafe', en: 'Could I get some hot water, please?', tr: 'Biraz sıcak su alabilir miyim?', context: 'Kafe', used: false }, color: '#9C6142' },
};
const PHRASES: Phrase[] = [
  { id: 'p1', en: 'Could you give me a hand with this?', tr: 'Bununla ilgili bana yardım eder misin?', context: 'Yardım isteme', used: true },
  { id: 'p2', en: 'I think the mic is not working.', tr: 'Sanırım mikrofon çalışmıyor.', context: 'Teknik sorun', used: true },
  { id: 'p3', en: 'Is there a plug nearby?', tr: 'Yakında bir priz var mı?', context: 'Kafe / çalışma', used: false },
];

export default function App({ defaultTab = 'home' }: { defaultTab?: Tab }) {
  const [tab, setTab] = useState<Tab>(defaultTab);
  const [chooser, setChooser] = useState(false);
  const [active, setActive] = useState(false);
  const [stage, setStage] = useState<Stage>('understand');
  const [scene, setScene] = useState<Scene>(SCENES.jury);
  const [alternatives, setAlternatives] = useState<Scene[]>([SCENES.jury]);
  const [analysis, setAnalysis] = useState<VisionAnalysis>(demoAnalysisFor(SCENES.jury));
  const [origin, setOrigin] = useState<MissionOrigin>({ mode: 'demo', visionLabel: 'Hazır demo bağlamı', scenarioLabel: 'LifeLens demo motoru' });
  const [pipelineStatus, setPipelineStatus] = useState<'idle' | 'vision' | 'scenario' | 'ready' | 'fallback'>('idle');
  const [imageUri, setImageUri] = useState<string | null>(null);
  const [scanning, setScanning] = useState(false);
  const [draft, setDraft] = useState('');
  const [twin, setTwin] = useState<Twin>({ directness: 82, warmth: 76, humour: 58 });
  const [level, setLevel] = useState<'A2' | 'B1'>('B1');
  const [privacy, setPrivacy] = useState(true);
  const [completed, setCompleted] = useState(6);
  const [phrases, setPhrases] = useState<Phrase[]>(PHRASES);
  const [history, setHistory] = useState<MissionRecord[]>([]);
  const [hydrated, setHydrated] = useState(false);
  const [chat, setChat] = useState<Chat[]>([{ id: 'opening', sender: 'coach', text: SCENES.jury.opening }]);
  const [partnerReply, setPartnerReply] = useState('');
  const feedback = useMemo(() => evaluatePractice(chat.filter((m) => m.sender === 'user').at(-1)?.text ?? '', twin, scene), [chat, scene, twin]);
  useEffect(() => { setTab(defaultTab); }, [defaultTab]);
  useEffect(() => {
    let subscribed = true;
    void loadLearningSnapshot().then((snapshot) => {
      if (!subscribed) return;
      if (snapshot) {
        setPhrases(snapshot.phrases);
        setTwin(snapshot.twin);
        setLevel(snapshot.level);
        setPrivacy(snapshot.privacy);
        setCompleted(snapshot.completed);
        setHistory(snapshot.history);
      }
      setHydrated(true);
    });
    return () => { subscribed = false; };
  }, []);
  useEffect(() => {
    if (!hydrated) return;
    const snapshot: LearningSnapshot = { schemaVersion: 1, phrases, twin, level, privacy, completed, history };
    void saveLearningSnapshot(snapshot);
  }, [completed, history, hydrated, level, phrases, privacy, twin]);
  const startDemo = (id: SceneId) => {
    const nextScene = SCENES[id];
    setScene(nextScene); setAlternatives([nextScene]); setAnalysis(demoAnalysisFor(nextScene)); setOrigin({ mode: 'demo', visionLabel: 'Hazır demo bağlamı', scenarioLabel: 'LifeLens demo motoru' }); setPipelineStatus('ready'); setImageUri(null);
    setChat([{ id: String(Date.now()), sender: 'coach', text: nextScene.opening }]); setPartnerReply(''); setDraft('');
    setActive(true); setStage('understand'); setScanning(true); setTimeout(() => setScanning(false), 620);
  };
  const startPhotoMission = async (image: { uri: string; base64: string; mimeType: string }) => {
    const processingScene: Scene = { ...SCENES.desk, id: `processing-${Date.now()}`, title: 'Fotoğrafın okunuyor', place: 'Seçtiğin ortam', confidence: 0, objects: [], context: 'Görüntü önce Gemini Vision tarafından görünür nesneler, ilişkiler ve belirsizlikler için inceleniyor.', mission: 'Preparing your mission', objective: 'Analiz tamamlandığında kişiselleştirilmiş görev burada görünecek.', opening: 'One moment — I am building a mission from your real-world context.' };
    setScene(processingScene); setAlternatives([processingScene]); setAnalysis(demoAnalysisFor(processingScene)); setOrigin({ mode: 'demo', visionLabel: 'Gemini Vision hazırlanıyor', scenarioLabel: 'Gemini 2.5 Flash-Lite hazırlanıyor' }); setImageUri(image.uri);
    setChat([{ id: String(Date.now()), sender: 'coach', text: processingScene.opening }]); setPartnerReply(''); setDraft(''); setActive(true); setStage('understand'); setScanning(true); setPipelineStatus('vision');
    const handoffTimer = setTimeout(() => setPipelineStatus((current) => current === 'vision' ? 'scenario' : current), 650);
    const result: PhotoMission = await createMissionFromPhoto({ image: { base64: image.base64, mimeType: image.mimeType }, level, twin });
    clearTimeout(handoffTimer);
    setScene(result.scene); setAlternatives(result.alternatives); setAnalysis(result.analysis); setOrigin(result.origin); setChat([{ id: String(Date.now()), sender: 'coach', text: result.scene.opening }]); setPartnerReply(''); setPipelineStatus(result.origin.mode === 'fallback' ? 'fallback' : 'ready'); setScanning(false);
  };
  const choosePhoto = async (source: 'camera' | 'library') => {
    if (!privacy) { setChooser(false); Alert.alert('Fotoğraf işlemesi kapalı', 'Profildeki gizlilik tercihin nedeniyle görsel gönderilmedi. Hazır demo sahnelerini yine kullanabilirsin.'); return; }
    setChooser(false);
    const permission = source === 'camera' ? await ImagePicker.requestCameraPermissionsAsync() : await ImagePicker.requestMediaLibraryPermissionsAsync();
    if (!permission.granted) { Alert.alert('İzin gerekli', 'Görsel seçmeden de hazır günlük yaşam sahneleriyle pratik yapabilirsin.'); return; }
    const options = { mediaTypes: ['images'] as ImagePicker.MediaType[], quality: 0.68, base64: true, exif: false };
    const result = source === 'camera' ? await ImagePicker.launchCameraAsync(options) : await ImagePicker.launchImageLibraryAsync(options);
    const asset = !result.canceled ? result.assets[0] : undefined;
    if (!asset) return;
    if (!asset.base64) { Alert.alert('Görsel hazırlanamadı', 'Fotoğraf verisi okunamadı. Lütfen yeniden deneyin.'); return; }
    void startPhotoMission({ uri: asset.uri, base64: asset.base64, mimeType: asset.mimeType ?? 'image/jpeg' });
  };
  const savePhrase = (phrase: Phrase) => setPhrases((all) => all.some((p) => p.en === phrase.en) ? all : [phrase, ...all]);
  const send = () => { const answer = draft.trim(); if (!answer) return; const reply = continuePracticeDialogue(answer, scene, twin); setChat((all) => [...all, { id: String(Date.now()), sender: 'user', text: answer }, { id: `${Date.now()}-reply`, sender: 'coach', text: reply }]); setPartnerReply(reply); setDraft(''); setStage('feedback'); };
  if (!hydrated) return <SafeAreaView style={s.safe}><StatusBar style="dark" /><View style={s.loading}><View style={s.loadingMark}><Text style={s.loadingMarkText}>◌</Text></View><ActivityIndicator color={C.teal}/><Text style={s.loadingTitle}>Kişisel öğrenme alanın hazırlanıyor</Text><Text style={s.loadingCopy}>İlerleme kayıtların güvenle yükleniyor.</Text></View></SafeAreaView>;
  return <SafeAreaView style={s.safe}><StatusBar style="dark" /><View style={s.app}>
    {active ? <Mission scene={scene} alternatives={alternatives} analysis={analysis} origin={origin} pipelineStatus={pipelineStatus} stage={stage} imageUri={imageUri} scanning={scanning} level={level} chat={chat} draft={draft} feedback={feedback} partnerReply={partnerReply} close={() => setActive(false)} changeStage={setStage} changeDraft={setDraft} send={send} save={() => savePhrase(scene.phrase)} chooseScenario={(nextScene) => { setScene(nextScene); setPartnerReply(''); setChat([{ id: String(Date.now()), sender: 'coach', text: nextScene.opening }]); }} finish={() => { savePhrase(scene.phrase); setHistory((items) => [{ id: String(Date.now()), sceneId: scene.id, title: scene.title, naturalness: feedback.naturalness, completedAt: new Date().toISOString() }, ...items].slice(0, 12)); setCompleted((n) => n + 1); setActive(false); setTab('home'); }} restart={() => imageUri ? setChooser(true) : startDemo('jury')} /> : <>
      {tab === 'home' && <Home completed={completed} phraseCount={phrases.length} latest={history[0]} capture={() => setChooser(true)} demo={() => startDemo('jury')} scene={startDemo} />}
      {tab === 'studio' && <Studio capture={() => setChooser(true)} scene={startDemo} />}
      {tab === 'library' && <Library phrases={phrases} remove={(id) => setPhrases((all) => all.filter((p) => p.id !== id))} />}
      {tab === 'twin' && <TwinScreen value={twin} change={setTwin} />}
      {tab === 'profile' && <Profile level={level} changeLevel={setLevel} privacy={privacy} changePrivacy={setPrivacy} />}
      <Nav tab={tab} change={setTab} />
    </>}
  </View>
  <Modal transparent animationType="slide" visible={chooser} onRequestClose={() => setChooser(false)}><Pressable style={s.backdrop} onPress={() => setChooser(false)}><Pressable style={s.sheet} onPress={() => undefined}><View style={s.handle}/><Text style={s.kicker}>SNAP & SPEAK · TWO-STAGE AI</Text><Text style={s.sheetTitle}>Bugün ne görüyorsun?</Text><Text style={s.sheetCopy}>Önce Gemini Vision görünür bağlamı çıkarır; ardından aynı API anahtarıyla çalışan Gemini 2.5 Flash-Lite bu analizden üç geniş senaryo önerir.</Text><View style={s.uploadPrivacy}><Text style={s.uploadPrivacyTitle}>GÖNDERİM NOTU</Text><Text style={s.uploadPrivacyCopy}>Demo ücretsiz Gemini katmanını kullanır. Kimlik, yüz, özel yazı veya hassas bilgi içeren fotoğrafları yükleme; görsel yalnızca görev üretimi için işlenir ve saklanmaz.</Text></View><Option icon="◉" title="Kamerayı aç" copy="Gerçek anını iki aşamada işle" color={C.tealPale} press={() => choosePhoto('camera')}/><Option icon="▣" title="Galeriden seç" copy="Fotoğrafı Gemini Vision'a gönder" color={C.amberPale} press={() => choosePhoto('library')}/><Option icon="✦" title="Jüri masası demosu" copy="Hazır bağlamla akışı anında göster" color={C.coralPale} press={() => { setChooser(false); startDemo('jury'); }}/></Pressable></Pressable></Modal>
  </SafeAreaView>;
}

function Home({ completed, phraseCount, latest, capture, demo, scene }: { completed: number; phraseCount: number; latest?: MissionRecord; capture: () => void; demo: () => void; scene: (id: SceneId) => void }) {
  return <ScrollView contentContainerStyle={s.screen} showsVerticalScrollIndicator={false}><Top/>
    <View style={s.heroRow}><View style={s.grow}><Text style={s.kicker}>PERSONAL LEARNING OS</Text><Text style={s.heroTitle}>Hayatın, sıradaki İngilizce dersin.</Text><Text style={s.heroCopy}>Kendi ortamından gelen durumlarla kısa ama gerçek konuşmalar yap.</Text></View><View style={s.orbit}><Text style={s.orbitText}>⌘</Text><View style={s.orbitDot}/></View></View>
    <Pressable style={s.captureCard} onPress={capture}><View style={s.orb1}/><View style={s.orb2}/><View style={s.captureTop}><View style={s.captureIcon}><Text style={s.captureIconText}>⌾</Text></View><View style={s.livePill}><View style={s.liveDot}/><Text style={s.liveText}>ÇEVRENDEN ÖĞREN</Text></View></View><Text style={s.captureTitle}>Bir anı yakala</Text><Text style={s.captureCopy}>Masan, mutfağın veya yoldaki küçük bir problem; hepsi konuşma pratiğine dönüşebilir.</Text><View style={s.captureButton}><Text style={s.captureButtonText}>Fotoğrafla başla</Text><Text style={s.captureArrow}>→</Text></View></Pressable>
    <Pressable style={s.demoCard} onPress={demo}><View style={s.demoSignal}><Text style={s.demoSignalText}>LIVE</Text></View><View style={s.grow}><Text style={s.demoKicker}>HACKATHON DEMO MODU</Text><Text style={s.demoTitle}>Jüri masasını canlı göreve dönüştür</Text><Text style={s.demoCopy}>Mikrofon · Su şişesi · Sunum</Text></View><Text style={s.demoArrow}>›</Text></Pressable>
    <Heading title="Bugünkü görünüm" note="Canlı ilerleme"/><View style={s.metrics}><Metric icon="↗" number={String(completed)} label="tamamlanan görev" color={C.tealPale}/><Metric icon="✦" number={String(phraseCount)} label="sana uyan ifade" color={C.amberPale}/><Metric icon="◌" number="82%" label="doğal konuşma" color={C.coralPale}/></View>
    <Heading title="Hızlı başlat" note="Hazır bağlamlar"/><View style={s.shortcuts}>{(['desk', 'cafe', 'jury'] as SceneId[]).map((id) => <Pressable key={id} style={[s.shortcut, { backgroundColor: SCENES[id].color }]} onPress={() => scene(id)}><Text style={s.shortcutIcon}>{SCENES[id].icon}</Text><Text style={s.shortcutTitle}>{SCENES[id].place}</Text><Text style={s.shortcutCopy}>{SCENES[id].objects.slice(0, 2).join(' · ')}</Text></Pressable>)}</View>
    <View style={s.mapCard}><View style={s.rowBetween}><View><Text style={s.mapKicker}>LIFE MAP</Text><Text style={s.mapTitle}>Hayatın sana nerede kelime öğretiyor?</Text></View><Text style={s.mapArrow}>›</Text></View><View style={s.bubbles}><Bubble label="Ev" value="32%" kind="big"/><Bubble label="Kafe" value="27%" kind="medium"/><Bubble label="Okul" value="24%" kind="small"/><Bubble label="Ofis" value="17%" kind="small"/></View></View>
    {latest && <View style={s.recent}><View style={s.recentIcon}><Text style={s.recentIconText}>✓</Text></View><View style={s.grow}><Text style={s.recentKicker}>SON TAMAMLANAN GÖREV</Text><Text style={s.recentTitle}>{latest.title}</Text><Text style={s.recentCopy}>{latest.naturalness}% doğallık · ifadelerin tekrar kuyruğuna eklendi</Text></View></View>}
  </ScrollView>;
}

function Studio({ capture, scene }: { capture: () => void; scene: (id: SceneId) => void }) {
  const flow = [['01', 'Yakalama', 'Fotoğrafını veya sahneni seç'], ['02', 'Anlama', 'Nesne + ilişki + bağlam'], ['03', 'Görev', 'Seviyene uygun hedef'], ['04', 'Konuşma', 'Yaz veya sesinle yanıtla'], ['05', 'Geri bildirim', 'Doğruluk, doğallık, sen']];
  return <ScrollView contentContainerStyle={s.screen} showsVerticalScrollIndicator={false}><Top/><Text style={s.kicker}>MISSION STUDIO</Text><Text style={s.heroTitle}>Bir fotoğraf, beş aşamalı pratik.</Text><Text style={s.heroCopy}>Nesne → bağlam → iletişim amacı → konuşma → sana uygun geri bildirim.</Text><View style={s.flow}>{flow.map(([n, t, c], i) => <View style={[s.flowItem, i === 0 && s.flowActive]} key={n}><Text style={[s.flowNumber, i === 0 && s.flowNumberActive]}>{n}</Text><View style={s.grow}><Text style={[s.flowTitle, i === 0 && s.flowTitleActive]}>{t}</Text><Text style={[s.flowCopy, i === 0 && s.flowCopyActive]}>{c}</Text></View></View>)}</View><Primary text="Kendi fotoğrafımla dene" press={capture}/><Heading title="Demo için hazır sahneler" note="Anında başlat"/>{(['desk', 'cafe', 'jury'] as SceneId[]).map((id) => <Pressable key={id} style={s.studioScene} onPress={() => scene(id)}><View style={[s.studioIcon, { backgroundColor: SCENES[id].color }]}><Text style={s.studioIconText}>{SCENES[id].icon}</Text></View><View style={s.grow}><Text style={s.sceneKicker}>{SCENES[id].place.toUpperCase()}</Text><Text style={s.studioTitle}>{SCENES[id].title}</Text><Text style={s.studioCopy}>{SCENES[id].objects.join(' · ')}</Text></View><Text style={s.studioArrow}>›</Text></Pressable>)}</ScrollView>;
}

function Mission({ scene, alternatives, analysis, origin, pipelineStatus, stage, imageUri, scanning, level, chat, draft, feedback, partnerReply, close, changeStage, changeDraft, send, save, chooseScenario, finish, restart }: { scene: Scene; alternatives: Scene[]; analysis: VisionAnalysis; origin: MissionOrigin; pipelineStatus: 'idle' | 'vision' | 'scenario' | 'ready' | 'fallback'; stage: Stage; imageUri: string | null; scanning: boolean; level: string; chat: Chat[]; draft: string; feedback: Evaluation; partnerReply: string; close: () => void; changeStage: (v: Stage) => void; changeDraft: (v: string) => void; send: () => void; save: () => void; chooseScenario: (scene: Scene) => void; finish: () => void; restart: () => void }) {
  const labels = ['Yakalama', 'Anlama', 'Görev', 'Konuşma', 'Geri bildirim']; const active = stage === 'understand' ? 1 : stage === 'mission' ? 2 : stage === 'speak' ? 3 : 4;
  return <View style={s.missionRoot}><View style={s.missionTop}><Pressable style={s.back} onPress={close}><Text style={s.backText}>‹</Text></Pressable><View style={s.grow}><Text style={s.missionKicker}>LIVE MISSION · {level}</Text><Text style={s.missionTitle}>{scene.title}</Text></View><View style={s.timer}><Text style={s.timerText}>06:30</Text></View></View><View style={s.stageRail}>{labels.map((label, i) => <View style={s.stageItem} key={label}><View style={[s.stageDot, i <= active && s.stageDotDone]}><Text style={[s.stageNumber, i <= active && s.stageNumberDone]}>{i < active ? '✓' : i + 1}</Text></View><Text numberOfLines={1} style={[s.stageLabel, i === active && s.stageLabelActive]}>{label}</Text></View>)}</View>
    <ScrollView contentContainerStyle={s.missionScroll} showsVerticalScrollIndicator={false}>
      <SceneView scene={scene} uri={imageUri} origin={origin}/>
      {stage === 'understand' && <Understand scene={scene} analysis={analysis} origin={origin} pipelineStatus={pipelineStatus} scanning={scanning} next={() => changeStage('mission')}/>}
      {stage === 'mission' && <MissionCard scene={scene} alternatives={alternatives} choose={chooseScenario} level={level} start={() => changeStage('speak')} save={save}/>}
      {stage === 'speak' && <Speak scene={scene} chat={chat} draft={draft} change={changeDraft} send={send}/>}
      {stage === 'feedback' && <Feedback result={feedback} partnerReply={partnerReply} finish={finish} restart={restart}/>}
    </ScrollView>
  </View>;
}
function SceneView({ scene, uri, origin }: { scene: Scene; uri: string | null; origin: MissionOrigin }) { const isLive = origin.mode === 'live'; return <View style={[s.sceneView, { backgroundColor: scene.color }]}>{uri ? <Image source={{ uri }} style={s.sceneImage}/> : <><View style={s.grid}/><View style={s.beam}/><Text style={s.bigIcon}>{scene.icon}</Text><View style={s.shape1}/><View style={s.shape2}/><View style={s.shape3}/></>}<View style={s.shade}/><View style={s.sceneTop}><View style={s.vision}><View style={s.visionDot}/><Text style={s.visionText}>{isLive ? 'GEMINI VISION' : 'CONTEXT PREVIEW'}</Text></View><Text style={s.confidence}>{scene.confidence ? `${scene.confidence}% güven` : 'işleniyor'}</Text></View><View style={s.sceneCaption}><Text style={s.sceneCaptionTitle}>{scene.objects.length ? scene.objects.join(' · ') : 'Görünür bağlam bekleniyor'}</Text><Text style={s.sceneCaptionCopy}>{scene.place} · {isLive ? 'iki model, tek doğrulanmış bağlam' : 'güvenli önizleme'}</Text></View></View>; }
function Understand({ scene, analysis, origin, pipelineStatus, scanning, next }: { scene: Scene; analysis: VisionAnalysis; origin: MissionOrigin; pipelineStatus: 'idle' | 'vision' | 'scenario' | 'ready' | 'fallback'; scanning: boolean; next: () => void }) {
  const statusCopy = pipelineStatus === 'vision' ? 'Gemini Vision görünür nesneleri, ortamı ve belirsizlikleri ayırıyor.' : pipelineStatus === 'scenario' ? 'Gemini 2.5 Flash-Lite, yalnızca bu analizi kullanarak üç geniş senaryo üretiyor.' : 'Nesneler, ortam ve olası iletişim ihtiyacı eşleştiriliyor.';
  const live = origin.mode === 'live';
  return <View style={s.card}><Kicker icon="◉" text="ADIM 02 · BAĞLAMI ANLAMA" color={C.teal}/>{scanning ? <View style={s.scanning}><ActivityIndicator color={C.teal}/><View style={s.grow}><Text style={s.scanTitle}>{pipelineStatus === 'scenario' ? 'Senaryoyu genişletiyorum' : 'Görüntüyü Gemini ile okuyorum'}</Text><Text style={s.scanCopy}>{statusCopy}</Text></View></View> : <><View style={s.pipeline}><View style={s.pipelineStep}><Text style={s.pipelineNo}>1</Text><View><Text style={s.pipelineTitle}>{origin.visionLabel}</Text><Text style={s.pipelineCopy}>{live ? 'Fotoğraf → görünür kanıt + belirsizlik' : analysis.model}</Text></View></View><Text style={s.pipelineArrow}>→</Text><View style={s.pipelineStep}><Text style={[s.pipelineNo, s.pipelineNoSecond]}>2</Text><View><Text style={s.pipelineTitle}>{origin.scenarioLabel}</Text><Text style={s.pipelineCopy}>Analiz → genişletilmiş konuşma görevi</Text></View></View></View><Text style={s.cardTitle}>{scene.objects[0] ? `Bu sadece ${scene.objects[0].toLowerCase()} değil.` : 'Görseli uydurmadan çalışıyoruz.'}</Text><Text style={s.cardCopy}>{scene.context}</Text>{analysis.objects.length > 0 && <><Text style={s.tagLabel}>GEMINI'NİN GÖRÜNÜR İPUÇLARI</Text><View style={s.tags}>{analysis.objects.map((item) => <View style={s.tag} key={item.label}><Text style={s.tagTick}>✓</Text><Text style={s.tagText}>{item.label} · %{item.confidence}</Text></View>)}</View></>}<View style={s.evidence}><Text style={s.evidenceTitle}>GÖRÜNÜR BAĞLAM</Text>{analysis.relationships.slice(0, 2).map((line) => <Text style={s.evidenceCopy} key={line}>• {line}</Text>)}</View><View style={s.notice}><Text style={s.noticeIcon}>✦</Text><Text style={s.noticeText}>{origin.notice ?? analysis.uncertainties[0] ?? 'LifeLens kesin olmayan detayları gerçekmiş gibi sunmaz; görev yalnızca görünür bağlamdan üretilir.'}</Text></View><Primary text="Genişletilmiş görevi gör" press={next}/></>}</View>;
}
function MissionCard({ scene, alternatives, choose, level, start, save }: { scene: Scene; alternatives: Scene[]; choose: (scene: Scene) => void; level: string; start: () => void; save: () => void }) { return <View style={s.card}><Kicker icon="✦" text="ADIM 03 · GÖREV HAZIR" color="#A46B0E"/>{alternatives.length > 1 && <View style={s.scenarioChoices}><Text style={s.scenarioChoicesLabel}>GEMINI 2.5 FLASH-LITE · 3 SENARYO</Text><Text style={s.scenarioChoicesCopy}>Aynı görünür bağlamdan çıkan rotalardan birini seçebilirsin.</Text>{alternatives.map((alternative, index) => <Pressable key={alternative.id} onPress={() => choose(alternative)} style={[s.scenarioChoice, alternative.id === scene.id && s.scenarioChoiceActive]}><View style={s.scenarioChoiceNumber}><Text style={s.scenarioChoiceNumberText}>{index + 1}</Text></View><View style={s.grow}><Text style={s.scenarioChoiceTitle}>{alternative.title}</Text><Text numberOfLines={2} style={s.scenarioChoiceCopy}>{alternative.objective}</Text></View>{alternative.id === scene.id && <Text style={s.scenarioSelected}>SEÇİLİ</Text>}</Pressable>)}</View>}<Text style={s.cardTitle}>{scene.mission}</Text><Text style={s.cardCopy}>{scene.objective}</Text><View style={s.goal}><View style={s.goalIcon}><Text style={s.goalIconText}>◎</Text></View><View style={s.grow}><Text style={s.goalLabel}>İLETİŞİM AMACI</Text><Text style={s.goalText}>Kısa biçimde durumu açıkla ve yardım iste.</Text></View></View><View style={s.phrasePreview}><View style={s.rowBetween}><Text style={s.previewLabel}>SENİN TONUNDA</Text><Pressable onPress={save}><Text style={s.save}>+ Kaydet</Text></Pressable></View><Text style={s.previewEn}>{scene.phrase.en}</Text><Text style={s.previewTr}>{scene.phrase.tr}</Text></View><View style={s.meta}><Meta text={level + ' · Speaking'} color={C.tealPale}/><Meta text="Kısa + samimi" color={C.amberPale}/></View><Primary text="Diyaloğu başlat" press={start}/></View>; }
function Speak({ scene, chat, draft, change, send }: { scene: Scene; chat: Chat[]; draft: string; change: (v: string) => void; send: () => void }) { return <View style={s.card}><View style={s.rowBetween}><Kicker icon="◌" text="ADIM 04 · KONUŞ" color={C.coral}/><View style={s.partner}><View style={s.partnerDot}/><Text style={s.partnerText}>{scene.partner}</Text></View></View><Text style={s.cardTitle}>Şimdi senin sıran.</Text><Text style={s.cardCopy}>İngilizce olarak doğal yanıtını yaz. Hata yapman görevin bir parçası.</Text><View style={s.chatArea}>{chat.map((m) => <ChatBubble key={m.id} message={m}/>)}</View><View style={s.tip}><Text style={s.tipStar}>✦</Text><Text style={s.tipText}>“I think…” ile sorunu belirt, ardından “Could you…” ile isteğini ekle.</Text></View><View style={s.inlineComposer}><TextInput value={draft} onChangeText={change} onSubmitEditing={send} style={s.inlineInput} placeholder="Yanıtını İngilizce yaz..." placeholderTextColor="#8A9AA1" multiline/><Pressable style={s.inlineSend} onPress={send}><Text style={s.inlineSendText}>↑</Text></Pressable></View></View>; }
function Feedback({ result, partnerReply, finish, restart }: { result: Evaluation; partnerReply: string; finish: () => void; restart: () => void }) { return <View style={s.card}><Kicker icon="✓" text="ADIM 05 · SENİN İNGİLİZCEN" color={C.teal}/><Text style={s.cardTitle}>Doğruya yakın; şimdi senin gibi duyulsun.</Text><Text style={s.cardCopy}>Yanıtın: “{result.answer}”</Text>{partnerReply ? <View style={s.tip}><Text style={s.tipStar}>◌</Text><Text style={s.tipText}>Konuşma partneri: “{partnerReply}”</Text></View> : null}<View style={s.scores}><Score label="Doğruluk" value={result.accuracy} color={C.teal}/><Score label="Doğallık" value={result.naturalness} color={C.amber}/><Score label="Tarz uyumu" value={result.voice} color={C.coral}/></View><FeedbackLine label="Dil doğruluğu" badge="Düzelt" body={result.grammar} quote={result.corrected} color={C.coral}/><FeedbackLine label="Doğallık" badge="Tarz seçeneği" body={result.natural} quote={result.style} color="#A46B0E"/><View style={s.twinNote}><View style={s.twinIcon}><Text style={s.twinIconText}>◌</Text></View><View style={s.grow}><Text style={s.twinNoteKicker}>İNGİLİZCE İKİZİN</Text><Text style={s.twinNoteText}>{result.style}</Text><Text style={s.twinNoteCopy}>Kısa, samimi ve net tonunu koruyor.</Text></View></View><Primary text="Görevi tamamla ve kaydet" press={finish}/><Pressable style={s.secondary} onPress={restart}><Text style={s.secondaryText}>Bu görevi yeniden dene</Text></Pressable></View>; }

function Library({ phrases, remove }: { phrases: Phrase[]; remove: (id: string) => void }) { const [query, setQuery] = useState(''); const list = phrases.filter((p) => (p.en + p.tr + p.context).toLocaleLowerCase('tr').includes(query.toLocaleLowerCase('tr'))); return <ScrollView contentContainerStyle={s.screen} showsVerticalScrollIndicator={false}><Top/><Text style={s.kicker}>MY ENGLISH, MY WORDS</Text><Text style={s.heroTitle}>Sana uyan sözler, tek yerde.</Text><Text style={s.heroCopy}>Her ifade nerede öğrendiğini ve senin tonunda nasıl çalıştığını hatırlar.</Text><View style={s.libStats}><LibraryStat icon="✦" num={String(phrases.length)} label="kaydedilen" color={C.tealPale}/><LibraryStat icon="↗" num={String(phrases.filter((p) => p.used).length)} label="kullanılan" color={C.coralPale}/><LibraryStat icon="⌁" num="3" label="ortam" color={C.amberPale}/></View><View style={s.search}><Text style={s.searchIcon}>⌕</Text><TextInput value={query} onChangeText={setQuery} style={s.searchInput} placeholder="İfade veya ortam ara" placeholderTextColor="#8A9AA1"/></View><Text style={s.listCaption}>{list.length} ifade · bağlamına göre saklandı</Text>{list.map((p) => <View style={s.phraseRow} key={p.id}><View style={s.phraseIcon}><Text style={s.phraseIconText}>{p.used ? '✓' : '✦'}</Text></View><View style={s.grow}><Text style={s.phraseEn}>{p.en}</Text><Text style={s.phraseTr}>{p.tr}</Text><View style={s.context}><Text style={s.contextText}>{p.context}</Text></View></View><Pressable style={s.remove} onPress={() => remove(p.id)}><Text style={s.removeText}>×</Text></Pressable></View>)}{!list.length && <View style={s.empty}><Text style={s.emptyIcon}>⌕</Text><Text style={s.emptyTitle}>Bu aramayla eşleşen ifade yok.</Text><Text style={s.emptyCopy}>Yeni görevleri tamamladığında sana uyan kalıpları burada bulacaksın.</Text></View>}</ScrollView>; }
function TwinScreen({ value, change }: { value: Twin; change: (v: Twin) => void }) {
  const [sample, setSample] = useState('Bugün kısa konuşacağım, çok uzatmayalım. Yardım edersen süper olur!');
  const [signals, setSignals] = useState<string[]>([]);
  const [confidence, setConfidence] = useState<number | null>(null);
  const shift = (key: keyof Twin, amount: number) => change({ ...value, [key]: Math.max(0, Math.min(100, value[key] + amount)) });
  const analyse = () => { const result = inferTwinFromTurkish(sample, value); if (result.confidence) change(result.twin); setSignals(result.signals); setConfidence(result.confidence || null); };
  const direct = value.directness >= 65;
  return <ScrollView contentContainerStyle={s.screen} showsVerticalScrollIndicator={false}><Top/><Text style={s.kicker}>YOUR ENGLISH TWIN</Text><Text style={s.heroTitle}>Başka biri gibi değil, kendin gibi konuş.</Text><Text style={s.heroCopy}>Bu profil psikolojik bir hüküm değil; yalnızca onaylayıp düzenleyebileceğin dil tercihleri tahmini.</Text><View style={s.twinHero}><View style={s.twinHeroBadge}><Text style={s.twinHeroBadgeText}>◌</Text></View><Text style={s.twinHeroTitle}>{direct ? 'Kısa, samimi, net' : 'Nazik, dengeli, açıklayıcı'}</Text><Text style={s.twinHeroCopy}>Türkçe anlatımını örnek ver; LifeLens kelime uzunluğu, doğrudanlık ve nezaket işaretlerinden başlangıç ayarı çıkarır.</Text><View style={s.confidencePill}><Text style={s.confidenceText}>Profil güveni · %{confidence ?? 0}</Text></View></View><View style={s.twinSample}><Text style={s.twinSampleTitle}>Türkçe bir örnek yaz</Text><Text style={s.twinSampleCopy}>Gününü veya bir fikrini 1–3 cümleyle anlat. Bu metin cihazında tercih ayarı için işlenir.</Text><TextInput value={sample} onChangeText={setSample} multiline style={s.twinInput} placeholder="Örn. Bugün..." placeholderTextColor="#8A9AA1"/><Pressable style={s.twinAction} onPress={analyse}><Text style={s.twinActionText}>Tarzımı çıkar</Text></Pressable>{signals.length ? <View style={s.twinSignals}>{signals.map((signal) => <Text style={s.twinSignal} key={signal}>• {signal}</Text>)}</View> : null}</View><Text style={s.sectionTitle}>Tarz ayarların</Text><Trait label="Doğrudanlık" hint="Kısa ve net cümleler" value={value.directness} color={C.teal} minus={() => shift('directness', -8)} plus={() => shift('directness', 8)}/><Trait label="Samimiyet" hint="Sıcak ve gündelik ton" value={value.warmth} color={C.coral} minus={() => shift('warmth', -8)} plus={() => shift('warmth', 8)}/><Trait label="Hafif mizah" hint="Oyunlu ama ölçülü ifade" value={value.humour} color={C.amber} minus={() => shift('humour', -8)} plus={() => shift('humour', 8)}/><Text style={[s.sectionTitle, { marginTop: 4 }]}>Aynı anlam, senin seçimin</Text><View style={s.tone}><Text style={s.toneMutedLabel}>RESMÎ VE UZAK</Text><Text style={s.toneMuted}>I respectfully decline your offer.</Text><View style={s.toneLine}/><Text style={s.toneActiveLabel}>SANA UYGUN</Text><Text style={s.toneActive}>{direct ? 'I’d pass on that, thanks.' : 'Thanks, but I’ll have to pass.'}</Text><Text style={s.toneNote}>{direct ? 'Kısa, saygılı ve doğal.' : 'Yumuşak, açık ve sana yakın.'}</Text></View></ScrollView>;
}
function Profile({ level, changeLevel, privacy, changePrivacy }: { level: 'A2' | 'B1'; changeLevel: (v: 'A2' | 'B1') => void; privacy: boolean; changePrivacy: (v: boolean) => void }) { return <ScrollView contentContainerStyle={s.screen} showsVerticalScrollIndicator={false}><Top/><View style={s.profileHeader}><View style={s.avatar}><Text style={s.avatarText}>A</Text></View><View style={s.grow}><Text style={s.kicker}>ÖĞRENME PROFİLİ</Text><Text style={s.profileName}>Alexandra</Text><Text style={s.profileMeta}>Türkçe → İngilizce · hedef: günlük konuşma</Text></View></View><View style={s.week}><View><Text style={s.weekKicker}>BU HAFTA</Text><Text style={s.weekTitle}>47 dakika gerçek hayat pratiği</Text><Text style={s.weekCopy}>3 farklı ortam · 6 tamamlanan görev</Text></View><View style={s.ring}><Text style={s.ringText}>72%</Text></View></View><Text style={s.sectionTitle}>Öğrenme seviyesi</Text><View style={s.levels}>{(['A2', 'B1'] as const).map((x) => <Pressable key={x} style={[s.level, level === x && s.levelActive]} onPress={() => changeLevel(x)}><Text style={[s.levelText, level === x && s.levelTextActive]}>{x} · {x === 'A2' ? 'Temel' : 'Orta'}</Text></Pressable>)}</View><Text style={s.sectionTitle}>Gizlilik kontrolü</Text><View style={s.privacy}><View style={s.privacyIcon}><Text style={s.privacyIconText}>◉</Text></View><View style={s.grow}><Text style={s.privacyTitle}>Fotoğrafı analiz için geçici olarak işle</Text><Text style={s.privacyCopy}>Açıkken görsel yalnızca görev üretimi için gönderilir ve uygulama tarafından kalıcı saklanmaz. Kapalıyken kamera ve galeri gönderimi engellenir.</Text></View><Switch value={privacy} onValueChange={changePrivacy} trackColor={{ false: '#D7E0E0', true: '#9FD8D1' }} thumbColor={privacy ? C.teal : '#F4F4F4'}/></View><View style={s.account}><Text style={s.accountIcon}>↗</Text><View style={s.grow}><Text style={s.accountTitle}>Verilerim ve hesabım</Text><Text style={s.accountCopy}>İndir, silme talebi oluştur veya izinlerini gözden geçir.</Text></View><Text style={s.accountArrow}>›</Text></View></ScrollView>; }

function Top() { return <View style={s.top}><View style={s.brand}><View style={s.logo}><Text style={s.logoText}>◌</Text></View><View><Text style={s.brandName}>LifeLens</Text><Text style={s.brandSub}>SEE · SPEAK · SOUND LIKE YOU</Text></View></View><View style={s.b1}><Text style={s.b1Text}>B1</Text></View></View>; }
function Nav({ tab, change }: { tab: Tab; change: (v: Tab) => void }) { const router = useRouter(); const items: [Tab, string, string, string][] = [['home', '⌂', 'Keşfet', '/'], ['studio', '◉', 'Stüdyo', '/studio'], ['library', '◫', 'İfadelerim', '/library'], ['twin', '◌', 'İkizim', '/twin'], ['profile', '◎', 'Profil', '/profile']]; return <View style={s.nav}>{items.map(([id, icon, label, href]) => <Pressable key={id} style={[s.navItem, tab === id && s.navActive]} onPress={() => { change(id); router.replace(href as never); }}><Text style={[s.navIcon, tab === id && s.navIconActive]}>{icon}</Text><Text style={[s.navLabel, tab === id && s.navLabelActive]}>{label}</Text></Pressable>)}</View>; }
function Primary({ text, press }: { text: string; press: () => void }) { return <Pressable style={s.primary} onPress={press}><Text style={s.primaryText}>{text}</Text><Text style={s.primaryArrow}>→</Text></Pressable>; }
function Heading({ title, note }: { title: string; note: string }) { return <View style={s.heading}><Text style={s.sectionTitle}>{title}</Text><Text style={s.sectionNote}>{note}</Text></View>; }
function Metric({ icon, number, label, color }: { icon: string; number: string; label: string; color: string }) { return <View style={[s.metric, { backgroundColor: color }]}><Text style={s.metricIcon}>{icon}</Text><Text style={s.metricNumber}>{number}</Text><Text style={s.metricLabel}>{label}</Text></View>; }
function Bubble({ label, value, kind }: { label: string; value: string; kind: 'big' | 'medium' | 'small' }) { return <View style={[s.bubble, kind === 'big' ? s.bubbleBig : kind === 'medium' ? s.bubbleMedium : s.bubbleSmall]}><Text style={s.bubbleLabel}>{label}</Text><Text style={s.bubbleValue}>{value}</Text></View>; }
function Option({ icon, title, copy, color, press }: { icon: string; title: string; copy: string; color: string; press: () => void }) { return <Pressable style={s.option} onPress={press}><View style={[s.optionIcon, { backgroundColor: color }]}><Text style={s.optionIconText}>{icon}</Text></View><View style={s.grow}><Text style={s.optionTitle}>{title}</Text><Text style={s.optionCopy}>{copy}</Text></View><Text style={s.optionArrow}>›</Text></Pressable>; }
function Kicker({ icon, text, color }: { icon: string; text: string; color: string }) { return <View style={s.cardKicker}><Text style={[s.cardKickerIcon, { color }]}>{icon}</Text><Text style={[s.cardKickerText, { color }]}>{text}</Text></View>; }
function Meta({ text, color }: { text: string; color: string }) { return <View style={[s.metaChip, { backgroundColor: color }]}><Text style={s.metaText}>{text}</Text></View>; }
function ChatBubble({ message }: { message: Chat }) { const coach = message.sender === 'coach'; return <View style={[s.chatRow, !coach && s.chatRight]}>{coach && <View style={s.chatAvatar}><Text style={s.chatAvatarText}>AI</Text></View>}<View style={[s.chatBubble, coach ? s.coachBubble : s.userBubble]}><Text style={[s.chatText, !coach && s.userText]}>{message.text}</Text></View></View>; }
function Score({ label, value, color }: { label: string; value: number; color: string }) { return <View style={s.score}><Text style={s.scoreLabel}>{label}</Text><Text style={[s.scoreValue, { color }]}>{value}%</Text><View style={s.scoreTrack}><View style={[s.scoreFill, { backgroundColor: color, width: `${value}%` as `${number}%` }]}/></View></View>; }
function FeedbackLine({ label, badge, body, quote, color }: { label: string; badge: string; body: string; quote: string; color: string }) { return <View style={s.feedbackLine}><View style={s.rowBetween}><Text style={s.feedbackLabel}>{label}</Text><View style={s.feedbackBadge}><Text style={[s.feedbackBadgeText, { color }]}>{badge}</Text></View></View><Text style={s.feedbackBody}>{body}</Text><Text style={s.feedbackQuote}>“{quote}”</Text></View>; }
function LibraryStat({ icon, num, label, color }: { icon: string; num: string; label: string; color: string }) { return <View style={[s.libStat, { backgroundColor: color }]}><Text style={s.libStatIcon}>{icon}</Text><Text style={s.libStatNum}>{num}</Text><Text style={s.libStatLabel}>{label}</Text></View>; }
function Trait({ label, hint, value, color, minus, plus }: { label: string; hint: string; value: number; color: string; minus: () => void; plus: () => void }) { return <View style={s.trait}><View style={s.rowBetween}><View><Text style={s.traitLabel}>{label}</Text><Text style={s.traitHint}>{hint}</Text></View><View style={s.traitControls}><Pressable style={s.traitButton} onPress={minus}><Text style={s.traitButtonText}>−</Text></Pressable><Text style={[s.traitValue, { color }]}>{value}%</Text><Pressable style={s.traitButton} onPress={plus}><Text style={s.traitButtonText}>+</Text></Pressable></View></View><View style={s.traitTrack}><View style={[s.traitFill, { backgroundColor: color, width: `${value}%` as `${number}%` }]}/></View></View>; }

const s = StyleSheet.create({
  safe:{flex:1,backgroundColor:C.white}, app:{flex:1,backgroundColor:C.white}, grow:{flex:1}, rowBetween:{alignItems:'center',flexDirection:'row',justifyContent:'space-between'}, screen:{gap:18,paddingHorizontal:20,paddingTop:14,paddingBottom:114}, loading:{alignItems:'center',flex:1,justifyContent:'center',padding:32}, loadingMark:{alignItems:'center',backgroundColor:C.navy,borderRadius:22,height:64,justifyContent:'center',marginBottom:20,width:64}, loadingMarkText:{color:C.amber,fontSize:39}, loadingTitle:{color:C.navy,fontSize:17,fontWeight:'900',marginTop:16}, loadingCopy:{color:C.slate,fontSize:12,marginTop:5,textAlign:'center'},
  top:{alignItems:'center',flexDirection:'row',justifyContent:'space-between'}, brand:{alignItems:'center',flexDirection:'row',gap:9}, logo:{alignItems:'center',backgroundColor:C.navy,borderRadius:13,height:38,justifyContent:'center',width:38}, logoText:{color:C.amber,fontSize:27,fontWeight:'700',lineHeight:29}, brandName:{color:C.navy,fontSize:18,fontWeight:'900',letterSpacing:-.35}, brandSub:{color:C.slate,fontSize:7.5,fontWeight:'800',letterSpacing:.65,marginTop:1}, b1:{backgroundColor:C.tealPale,borderRadius:99,paddingHorizontal:12,paddingVertical:7}, b1Text:{color:C.teal,fontSize:12,fontWeight:'900'},
  kicker:{color:C.teal,fontSize:10,fontWeight:'900',letterSpacing:1.1}, heroRow:{alignItems:'flex-start',flexDirection:'row',marginTop:7}, heroTitle:{color:C.ink,fontSize:29,fontWeight:'900',letterSpacing:-.8,lineHeight:34,marginTop:6}, heroCopy:{color:C.slate,fontSize:13,lineHeight:19,marginTop:8,maxWidth:'94%'}, orbit:{alignItems:'center',backgroundColor:C.amberPale,borderRadius:28,height:56,justifyContent:'center',marginTop:6,overflow:'hidden',width:56}, orbitText:{color:'#A06A13',fontSize:28,fontWeight:'900'}, orbitDot:{backgroundColor:C.coral,borderRadius:5,height:10,position:'absolute',right:7,top:7,width:10},
  captureCard:{backgroundColor:C.tealPale,borderRadius:26,minHeight:246,overflow:'hidden',padding:22}, orb1:{backgroundColor:'#BFE8E0',borderRadius:145,height:230,position:'absolute',right:-90,top:-100,width:230}, orb2:{backgroundColor:'#F8DB9D',borderRadius:88,bottom:-73,height:176,position:'absolute',right:4,width:176}, captureTop:{alignItems:'center',flexDirection:'row',justifyContent:'space-between'}, captureIcon:{alignItems:'center',backgroundColor:C.white,borderRadius:16,height:49,justifyContent:'center',width:49}, captureIconText:{color:C.teal,fontSize:31,fontWeight:'700'}, livePill:{alignItems:'center',backgroundColor:'rgba(255,255,255,.78)',borderRadius:99,flexDirection:'row',gap:5,paddingHorizontal:9,paddingVertical:6}, liveDot:{backgroundColor:C.coral,borderRadius:4,height:7,width:7}, liveText:{color:C.navy,fontSize:8,fontWeight:'900',letterSpacing:.5}, captureTitle:{color:C.navy,fontSize:25,fontWeight:'900',letterSpacing:-.55,marginTop:20}, captureCopy:{color:'#315F62',fontSize:13,lineHeight:19,marginTop:7,maxWidth:'86%'}, captureButton:{alignItems:'center',alignSelf:'flex-start',backgroundColor:C.teal,borderRadius:13,flexDirection:'row',gap:10,marginTop:18,paddingHorizontal:15,paddingVertical:11}, captureButtonText:{color:C.white,fontSize:13,fontWeight:'900'}, captureArrow:{color:C.white,fontSize:17,fontWeight:'900'},
  demoCard:{alignItems:'center',backgroundColor:C.navy,borderRadius:20,flexDirection:'row',gap:12,padding:15}, demoSignal:{alignItems:'center',backgroundColor:C.coral,borderRadius:11,height:39,justifyContent:'center',width:39}, demoSignalText:{color:C.white,fontSize:8,fontWeight:'900'}, demoKicker:{color:C.amber,fontSize:8,fontWeight:'900',letterSpacing:.75}, demoTitle:{color:C.white,fontSize:14,fontWeight:'800',lineHeight:19,marginTop:3}, demoCopy:{color:'#C7D8E1',fontSize:10,marginTop:3}, demoArrow:{color:C.amber,fontSize:27},
  heading:{alignItems:'baseline',flexDirection:'row',justifyContent:'space-between',marginTop:3}, sectionTitle:{color:C.ink,fontSize:17,fontWeight:'900'}, sectionNote:{color:C.slate,fontSize:10,fontWeight:'700'}, metrics:{flexDirection:'row',gap:9}, metric:{borderRadius:17,flex:1,minHeight:116,padding:13}, metricIcon:{color:C.navy,fontSize:18,fontWeight:'900'}, metricNumber:{color:C.navy,fontSize:22,fontWeight:'900',marginTop:8}, metricLabel:{color:C.slate,fontSize:10,fontWeight:'700',lineHeight:14,marginTop:3}, shortcuts:{flexDirection:'row',gap:9}, shortcut:{borderRadius:17,flex:1,minHeight:124,overflow:'hidden',padding:12}, shortcutIcon:{color:C.amber,fontSize:23}, shortcutTitle:{color:C.white,fontSize:13,fontWeight:'900',marginTop:16}, shortcutCopy:{color:'#D4E0E3',fontSize:9,lineHeight:12,marginTop:4},
  mapCard:{backgroundColor:C.mist,borderRadius:22,padding:17}, mapKicker:{color:C.teal,fontSize:9,fontWeight:'900',letterSpacing:.8}, mapTitle:{color:C.ink,fontSize:15,fontWeight:'900',lineHeight:20,marginTop:4,maxWidth:260}, mapArrow:{color:C.teal,fontSize:26}, bubbles:{alignItems:'flex-end',flexDirection:'row',gap:9,justifyContent:'center',marginTop:17}, bubble:{alignItems:'center',backgroundColor:C.white,borderRadius:99,justifyContent:'center'}, bubbleBig:{height:83,width:83}, bubbleMedium:{backgroundColor:C.tealPale,height:69,width:69}, bubbleSmall:{backgroundColor:C.amberPale,height:55,width:55}, bubbleLabel:{color:C.ink,fontSize:10,fontWeight:'900'}, bubbleValue:{color:C.slate,fontSize:9,marginTop:2}, recent:{alignItems:'center',backgroundColor:C.white,borderColor:C.line,borderRadius:17,borderWidth:1,flexDirection:'row',gap:11,padding:13}, recentIcon:{alignItems:'center',backgroundColor:C.tealPale,borderRadius:12,height:39,justifyContent:'center',width:39}, recentIconText:{color:C.teal,fontSize:16,fontWeight:'900'}, recentKicker:{color:C.teal,fontSize:8.5,fontWeight:'900',letterSpacing:.55}, recentTitle:{color:C.ink,fontSize:13,fontWeight:'900',marginTop:3}, recentCopy:{color:C.slate,fontSize:10,lineHeight:14,marginTop:3},
  nav:{backgroundColor:C.white,borderTopColor:'#E6EEEE',borderTopWidth:1,bottom:0,flexDirection:'row',left:0,paddingBottom:Platform.select({ios:10,default:7}),paddingHorizontal:4,paddingTop:8,position:'absolute',right:0}, navItem:{alignItems:'center',borderRadius:11,flex:1,gap:2,paddingVertical:3}, navActive:{backgroundColor:'#EAF6F3'}, navIcon:{color:'#91A0A7',fontSize:19}, navIconActive:{color:C.teal}, navLabel:{color:'#87959C',fontSize:8.5,fontWeight:'800'}, navLabelActive:{color:C.teal},
  flow:{backgroundColor:C.mist,borderRadius:21,gap:7,padding:12}, flowItem:{alignItems:'center',borderRadius:14,flexDirection:'row',gap:11,padding:10}, flowActive:{backgroundColor:C.navy}, flowNumber:{color:C.slate,fontSize:12,fontWeight:'900',width:22}, flowNumberActive:{color:C.amber}, flowTitle:{color:C.ink,fontSize:13,fontWeight:'900'}, flowTitleActive:{color:C.white}, flowCopy:{color:C.slate,fontSize:10,marginTop:2}, flowCopyActive:{color:'#C5D7DF'}, primary:{alignItems:'center',backgroundColor:C.navy,borderRadius:15,flexDirection:'row',justifyContent:'space-between',paddingHorizontal:17,paddingVertical:16}, primaryText:{color:C.white,fontSize:14,fontWeight:'900'}, primaryArrow:{color:C.amber,fontSize:18,fontWeight:'900'}, studioScene:{alignItems:'center',borderBottomColor:C.line,borderBottomWidth:1,flexDirection:'row',gap:12,paddingVertical:13}, studioIcon:{alignItems:'center',borderRadius:15,height:50,justifyContent:'center',width:50}, studioIconText:{color:C.white,fontSize:23}, sceneKicker:{color:C.teal,fontSize:8,fontWeight:'900',letterSpacing:.7}, studioTitle:{color:C.ink,fontSize:15,fontWeight:'900',marginTop:2}, studioCopy:{color:C.slate,fontSize:10,marginTop:3}, studioArrow:{color:C.navy,fontSize:27},
  missionRoot:{backgroundColor:C.mist,flex:1}, missionTop:{alignItems:'center',backgroundColor:C.white,flexDirection:'row',gap:10,paddingHorizontal:15,paddingVertical:13}, back:{alignItems:'center',backgroundColor:C.mist,borderRadius:20,height:35,justifyContent:'center',width:35}, backText:{color:C.navy,fontSize:28,lineHeight:29}, missionKicker:{color:C.teal,fontSize:8.5,fontWeight:'900',letterSpacing:.7}, missionTitle:{color:C.ink,fontSize:14,fontWeight:'900',marginTop:2}, timer:{backgroundColor:C.amberPale,borderRadius:8,paddingHorizontal:9,paddingVertical:6}, timerText:{color:'#A46B0E',fontSize:11,fontWeight:'900'}, stageRail:{backgroundColor:C.white,borderTopColor:'#ECF0F1',borderTopWidth:1,flexDirection:'row',paddingHorizontal:9,paddingVertical:10}, stageItem:{alignItems:'center',flex:1,gap:4}, stageDot:{alignItems:'center',backgroundColor:'#E6EEEE',borderRadius:10,height:20,justifyContent:'center',width:20}, stageDotDone:{backgroundColor:C.teal}, stageNumber:{color:'#718089',fontSize:9,fontWeight:'900'}, stageNumberDone:{color:C.white}, stageLabel:{color:'#7C8A91',fontSize:7.5,fontWeight:'800',maxWidth:58}, stageLabelActive:{color:C.teal}, missionScroll:{gap:15,padding:16,paddingBottom:28},
  sceneView:{borderRadius:21,height:210,overflow:'hidden'}, sceneImage:{height:'100%',width:'100%'}, grid:{borderColor:'rgba(255,255,255,.12)',borderWidth:1,height:300,left:60,position:'absolute',top:-50,transform:[{rotate:'45deg'}],width:300}, beam:{backgroundColor:'rgba(243,175,61,.25)',borderRadius:80,height:160,position:'absolute',right:-35,top:-35,width:160}, bigIcon:{color:C.white,fontSize:70,left:30,position:'absolute',top:54}, shape1:{backgroundColor:'rgba(255,255,255,.40)',borderRadius:7,bottom:43,height:15,position:'absolute',right:34,width:92}, shape2:{backgroundColor:'rgba(243,175,61,.75)',borderRadius:7,bottom:65,height:13,position:'absolute',right:60,width:44}, shape3:{backgroundColor:'rgba(255,255,255,.55)',borderRadius:20,bottom:39,height:37,position:'absolute',right:118,width:37}, shade:{backgroundColor:'rgba(3,21,34,.30)',bottom:0,left:0,position:'absolute',right:0,top:0}, sceneTop:{alignItems:'center',flexDirection:'row',justifyContent:'space-between',left:13,position:'absolute',right:13,top:13}, vision:{alignItems:'center',backgroundColor:'rgba(255,255,255,.88)',borderRadius:8,flexDirection:'row',gap:5,paddingHorizontal:8,paddingVertical:5}, visionDot:{backgroundColor:C.teal,borderRadius:4,height:7,width:7}, visionText:{color:C.navy,fontSize:8,fontWeight:'900',letterSpacing:.5}, confidence:{color:C.white,fontSize:9,fontWeight:'900'}, sceneCaption:{bottom:15,left:16,position:'absolute'}, sceneCaptionTitle:{color:C.white,fontSize:17,fontWeight:'900'}, sceneCaptionCopy:{color:'#E7F0F0',fontSize:10,marginTop:3},
  card:{backgroundColor:C.white,borderRadius:20,gap:14,padding:16}, cardKicker:{alignItems:'center',flexDirection:'row',gap:6}, cardKickerIcon:{fontSize:15,fontWeight:'900'}, cardKickerText:{fontSize:9,fontWeight:'900',letterSpacing:.65}, scanning:{alignItems:'center',backgroundColor:C.mist,borderRadius:14,flexDirection:'row',gap:12,padding:14}, scanTitle:{color:C.navy,fontSize:13,fontWeight:'900'}, scanCopy:{color:C.slate,fontSize:10,lineHeight:14,marginTop:3}, pipeline:{alignItems:'center',backgroundColor:'#EEF7F6',borderRadius:14,flexDirection:'row',gap:6,padding:10}, pipelineStep:{alignItems:'center',flex:1,flexDirection:'row',gap:6}, pipelineNo:{alignItems:'center',backgroundColor:C.teal,borderRadius:10,color:C.white,fontSize:10,fontWeight:'900',height:20,paddingTop:4,textAlign:'center',width:20}, pipelineNoSecond:{backgroundColor:C.navy}, pipelineTitle:{color:C.navy,fontSize:9.5,fontWeight:'900'}, pipelineCopy:{color:C.slate,fontSize:8.5,lineHeight:11,marginTop:2}, pipelineArrow:{color:C.teal,fontSize:15,fontWeight:'900'}, cardTitle:{color:C.ink,fontSize:21,fontWeight:'900',letterSpacing:-.35,lineHeight:26}, cardCopy:{color:C.slate,fontSize:13,lineHeight:19,marginTop:-7}, tagLabel:{color:C.slate,fontSize:9,fontWeight:'900',letterSpacing:.65,marginTop:2}, tags:{flexDirection:'row',flexWrap:'wrap',gap:7}, tag:{alignItems:'center',backgroundColor:C.mist,borderRadius:99,flexDirection:'row',gap:4,paddingHorizontal:9,paddingVertical:7}, tagTick:{color:C.teal,fontSize:10,fontWeight:'900'}, tagText:{color:C.ink,fontSize:11,fontWeight:'800'}, evidence:{backgroundColor:'#F5F8FA',borderLeftColor:C.teal,borderLeftWidth:3,borderRadius:10,gap:4,padding:10}, evidenceTitle:{color:C.teal,fontSize:8.5,fontWeight:'900',letterSpacing:.7}, evidenceCopy:{color:C.slate,fontSize:10,lineHeight:14}, notice:{alignItems:'flex-start',backgroundColor:C.amberPale,borderRadius:13,flexDirection:'row',gap:8,padding:11}, noticeIcon:{color:'#A46B0E',fontSize:14}, noticeText:{color:'#69501E',flex:1,fontSize:10,lineHeight:14},
  scenarioChoices:{backgroundColor:'#F5F8FA',borderColor:C.line,borderRadius:15,borderWidth:1,gap:8,padding:11}, scenarioChoicesLabel:{color:C.teal,fontSize:8.5,fontWeight:'900',letterSpacing:.7}, scenarioChoicesCopy:{color:C.slate,fontSize:10,lineHeight:14,marginBottom:2}, scenarioChoice:{alignItems:'center',backgroundColor:C.white,borderColor:'#E3EBEC',borderRadius:12,borderWidth:1,flexDirection:'row',gap:8,padding:9}, scenarioChoiceActive:{backgroundColor:C.tealPale,borderColor:C.teal}, scenarioChoiceNumber:{alignItems:'center',backgroundColor:C.navy,borderRadius:10,height:21,justifyContent:'center',width:21}, scenarioChoiceNumberText:{color:C.white,fontSize:10,fontWeight:'900'}, scenarioChoiceTitle:{color:C.ink,fontSize:11,fontWeight:'900'}, scenarioChoiceCopy:{color:C.slate,fontSize:9,lineHeight:12,marginTop:2}, scenarioSelected:{color:C.teal,fontSize:7.5,fontWeight:'900',letterSpacing:.4}, goal:{alignItems:'center',backgroundColor:C.mist,borderRadius:15,flexDirection:'row',gap:10,padding:12}, goalIcon:{alignItems:'center',backgroundColor:C.amberPale,borderRadius:12,height:39,justifyContent:'center',width:39}, goalIconText:{color:'#A46B0E',fontSize:20}, goalLabel:{color:C.coral,fontSize:8.5,fontWeight:'900',letterSpacing:.6}, goalText:{color:C.ink,fontSize:12,fontWeight:'800',lineHeight:16,marginTop:3}, phrasePreview:{backgroundColor:C.tealPale,borderRadius:16,padding:13}, previewLabel:{color:C.teal,fontSize:8.5,fontWeight:'900',letterSpacing:.65}, save:{color:C.teal,fontSize:10,fontWeight:'900'}, previewEn:{color:C.navy,fontSize:15,fontWeight:'900',lineHeight:20,marginTop:8}, previewTr:{color:'#436E6F',fontSize:11,lineHeight:15,marginTop:3}, meta:{flexDirection:'row',gap:7}, metaChip:{borderRadius:99,paddingHorizontal:9,paddingVertical:7}, metaText:{color:C.navy,fontSize:10,fontWeight:'900'},
  partner:{alignItems:'center',backgroundColor:'#E9F5F1',borderRadius:99,flexDirection:'row',gap:5,paddingHorizontal:8,paddingVertical:5}, partnerDot:{backgroundColor:C.teal,borderRadius:4,height:7,width:7}, partnerText:{color:C.teal,fontSize:8.5,fontWeight:'900'}, chatArea:{gap:10}, chatRow:{alignItems:'flex-end',flexDirection:'row',gap:7}, chatRight:{justifyContent:'flex-end'}, chatAvatar:{alignItems:'center',backgroundColor:C.coral,borderRadius:13,height:27,justifyContent:'center',width:27}, chatAvatarText:{color:C.white,fontSize:8,fontWeight:'900'}, chatBubble:{borderRadius:14,maxWidth:'83%',paddingHorizontal:12,paddingVertical:10}, coachBubble:{backgroundColor:C.mist,borderBottomLeftRadius:3}, userBubble:{backgroundColor:C.teal,borderBottomRightRadius:3}, chatText:{color:C.ink,fontSize:12.5,lineHeight:18}, userText:{color:C.white}, tip:{alignItems:'flex-start',backgroundColor:C.amberPale,borderRadius:12,flexDirection:'row',gap:7,padding:11}, tipStar:{color:'#A46B0E',fontSize:13}, tipText:{color:'#665020',flex:1,fontSize:10,lineHeight:14}, inlineComposer:{alignItems:'flex-end',backgroundColor:C.mist,borderRadius:15,flexDirection:'row',gap:6,padding:6,paddingLeft:12}, inlineInput:{color:C.ink,flex:1,fontSize:12,maxHeight:80,minHeight:36,paddingTop:9}, inlineSend:{alignItems:'center',backgroundColor:C.teal,borderRadius:11,height:35,justifyContent:'center',width:35}, inlineSendText:{color:C.white,fontSize:20,fontWeight:'900'},
  scores:{flexDirection:'row',gap:8}, score:{flex:1}, scoreLabel:{color:C.slate,fontSize:9,fontWeight:'800'}, scoreValue:{fontSize:14,fontWeight:'900',marginTop:2}, scoreTrack:{backgroundColor:C.mist,borderRadius:3,height:5,marginTop:6,overflow:'hidden'}, scoreFill:{borderRadius:3,height:'100%'}, feedbackLine:{borderTopColor:C.line,borderTopWidth:1,gap:6,paddingTop:12}, feedbackLabel:{color:C.ink,fontSize:12,fontWeight:'900'}, feedbackBadge:{backgroundColor:C.mist,borderRadius:99,paddingHorizontal:7,paddingVertical:4}, feedbackBadgeText:{fontSize:8.5,fontWeight:'900'}, feedbackBody:{color:C.slate,fontSize:11,lineHeight:16}, feedbackQuote:{color:C.navy,fontSize:13,fontWeight:'900',lineHeight:18}, twinNote:{alignItems:'flex-start',backgroundColor:C.tealPale,borderRadius:15,flexDirection:'row',gap:10,padding:12}, twinIcon:{alignItems:'center',backgroundColor:C.navy,borderRadius:12,height:35,justifyContent:'center',width:35}, twinIconText:{color:C.amber,fontSize:22}, twinNoteKicker:{color:C.teal,fontSize:8.5,fontWeight:'900',letterSpacing:.6}, twinNoteText:{color:C.navy,fontSize:13,fontWeight:'900',lineHeight:18,marginTop:3}, twinNoteCopy:{color:'#416C6D',fontSize:10,marginTop:4}, secondary:{alignItems:'center',borderColor:C.line,borderRadius:14,borderWidth:1,padding:14}, secondaryText:{color:C.navy,fontSize:12,fontWeight:'900'},
  libStats:{flexDirection:'row',gap:9}, libStat:{borderRadius:16,flex:1,minHeight:94,padding:12}, libStatIcon:{color:C.navy,fontSize:16}, libStatNum:{color:C.navy,fontSize:20,fontWeight:'900',marginTop:7}, libStatLabel:{color:C.slate,fontSize:10,fontWeight:'700',marginTop:2}, search:{alignItems:'center',backgroundColor:C.mist,borderRadius:13,flexDirection:'row',gap:8,paddingHorizontal:12}, searchIcon:{color:C.teal,fontSize:23}, searchInput:{color:C.ink,flex:1,fontSize:12.5,height:44}, listCaption:{color:C.slate,fontSize:10,fontWeight:'700',marginTop:-4}, phraseRow:{alignItems:'flex-start',borderBottomColor:C.line,borderBottomWidth:1,flexDirection:'row',gap:10,paddingVertical:14}, phraseIcon:{alignItems:'center',backgroundColor:C.amberPale,borderRadius:11,height:36,justifyContent:'center',width:36}, phraseIconText:{color:'#A46B0E',fontSize:14,fontWeight:'900'}, phraseEn:{color:C.ink,fontSize:13,fontWeight:'900',lineHeight:18}, phraseTr:{color:C.slate,fontSize:11,lineHeight:15,marginTop:3}, context:{alignSelf:'flex-start',backgroundColor:C.tealPale,borderRadius:99,marginTop:6,paddingHorizontal:7,paddingVertical:4}, contextText:{color:C.teal,fontSize:8.5,fontWeight:'900'}, remove:{alignItems:'center',backgroundColor:C.mist,borderRadius:13,height:26,justifyContent:'center',width:26}, removeText:{color:C.coral,fontSize:18}, empty:{alignItems:'center',backgroundColor:C.mist,borderRadius:18,padding:24}, emptyIcon:{color:C.teal,fontSize:27}, emptyTitle:{color:C.ink,fontSize:13,fontWeight:'900',marginTop:7}, emptyCopy:{color:C.slate,fontSize:11,lineHeight:16,marginTop:4,textAlign:'center'},
  twinHero:{backgroundColor:C.tealPale,borderRadius:22,padding:19}, twinHeroBadge:{alignItems:'center',backgroundColor:C.navy,borderRadius:16,height:48,justifyContent:'center',width:48}, twinHeroBadgeText:{color:C.amber,fontSize:30}, twinHeroTitle:{color:C.navy,fontSize:21,fontWeight:'900',marginTop:13}, twinHeroCopy:{color:'#3B6667',fontSize:12,lineHeight:18,marginTop:6}, confidencePill:{alignSelf:'flex-start',backgroundColor:'rgba(255,255,255,.75)',borderRadius:99,marginTop:13,paddingHorizontal:8,paddingVertical:6}, confidenceText:{color:C.teal,fontSize:9,fontWeight:'900'}, twinSample:{backgroundColor:C.mist,borderRadius:19,padding:15}, twinSampleTitle:{color:C.ink,fontSize:14,fontWeight:'900'}, twinSampleCopy:{color:C.slate,fontSize:10.5,lineHeight:15,marginTop:4}, twinInput:{backgroundColor:C.white,borderColor:C.line,borderRadius:12,borderWidth:1,color:C.ink,fontSize:12,lineHeight:17,marginTop:11,minHeight:76,padding:10,textAlignVertical:'top'}, twinAction:{alignItems:'center',alignSelf:'flex-start',backgroundColor:C.navy,borderRadius:10,marginTop:9,paddingHorizontal:13,paddingVertical:9}, twinActionText:{color:C.white,fontSize:11,fontWeight:'900'}, twinSignals:{borderTopColor:C.line,borderTopWidth:1,marginTop:11,paddingTop:8}, twinSignal:{color:C.slate,fontSize:10,lineHeight:15}, trait:{backgroundColor:C.white,borderBottomColor:C.line,borderBottomWidth:1,gap:9,paddingVertical:13}, traitLabel:{color:C.ink,fontSize:13,fontWeight:'900'}, traitHint:{color:C.slate,fontSize:10,marginTop:3}, traitControls:{alignItems:'center',flexDirection:'row',gap:8}, traitButton:{alignItems:'center',backgroundColor:C.mist,borderRadius:12,height:25,justifyContent:'center',width:25}, traitButtonText:{color:C.navy,fontSize:17,fontWeight:'900'}, traitValue:{fontSize:12,fontWeight:'900',minWidth:32,textAlign:'center'}, traitTrack:{backgroundColor:C.mist,borderRadius:4,height:7,overflow:'hidden'}, traitFill:{borderRadius:4,height:'100%'}, tone:{backgroundColor:C.mist,borderRadius:19,padding:16}, toneMutedLabel:{color:'#8C999E',fontSize:8.5,fontWeight:'900',letterSpacing:.7}, toneMuted:{color:C.slate,fontSize:13,marginTop:5}, toneLine:{backgroundColor:C.line,height:1,marginVertical:14}, toneActiveLabel:{color:C.teal,fontSize:8.5,fontWeight:'900',letterSpacing:.7}, toneActive:{color:C.ink,fontSize:16,fontWeight:'900',lineHeight:21,marginTop:5}, toneNote:{color:C.slate,fontSize:11,marginTop:4},
  profileHeader:{alignItems:'center',flexDirection:'row',gap:13,marginTop:6}, avatar:{alignItems:'center',backgroundColor:C.coral,borderRadius:32,height:63,justifyContent:'center',width:63}, avatarText:{color:C.white,fontSize:25,fontWeight:'900'}, profileName:{color:C.ink,fontSize:23,fontWeight:'900',marginTop:2}, profileMeta:{color:C.slate,fontSize:11,marginTop:3}, week:{alignItems:'center',backgroundColor:C.navy,borderRadius:21,flexDirection:'row',justifyContent:'space-between',padding:18}, weekKicker:{color:C.amber,fontSize:8.5,fontWeight:'900',letterSpacing:.7}, weekTitle:{color:C.white,fontSize:16,fontWeight:'900',lineHeight:21,marginTop:5,maxWidth:220}, weekCopy:{color:'#C5D7DF',fontSize:10,marginTop:5}, ring:{alignItems:'center',borderColor:C.amber,borderRadius:29,borderWidth:4,height:58,justifyContent:'center',width:58}, ringText:{color:C.white,fontSize:12,fontWeight:'900'}, levels:{backgroundColor:C.mist,borderRadius:14,flexDirection:'row',padding:4}, level:{alignItems:'center',borderRadius:11,flex:1,paddingVertical:11}, levelActive:{backgroundColor:C.navy}, levelText:{color:C.slate,fontSize:12,fontWeight:'900'}, levelTextActive:{color:C.white}, privacy:{alignItems:'flex-start',backgroundColor:C.mist,borderRadius:17,flexDirection:'row',gap:10,padding:13}, privacyIcon:{alignItems:'center',backgroundColor:C.tealPale,borderRadius:11,height:36,justifyContent:'center',width:36}, privacyIconText:{color:C.teal,fontSize:17}, privacyTitle:{color:C.ink,fontSize:12,fontWeight:'900',lineHeight:17,paddingRight:4}, privacyCopy:{color:C.slate,fontSize:10,lineHeight:14,marginTop:4}, account:{alignItems:'center',borderBottomColor:C.line,borderBottomWidth:1,flexDirection:'row',gap:11,paddingVertical:12}, accountIcon:{backgroundColor:C.amberPale,borderRadius:11,color:'#A46B0E',fontSize:17,height:36,paddingTop:8,textAlign:'center',width:36}, accountTitle:{color:C.ink,fontSize:13,fontWeight:'900'}, accountCopy:{color:C.slate,fontSize:10,lineHeight:14,marginTop:3}, accountArrow:{color:C.navy,fontSize:26},
  backdrop:{backgroundColor:'rgba(9,45,70,.48)',flex:1,justifyContent:'flex-end'}, sheet:{backgroundColor:C.white,borderTopLeftRadius:27,borderTopRightRadius:27,padding:22,paddingBottom:34}, handle:{alignSelf:'center',backgroundColor:'#D4DFDF',borderRadius:3,height:5,marginBottom:17,width:45}, sheetTitle:{color:C.ink,fontSize:23,fontWeight:'900',marginTop:4}, sheetCopy:{color:C.slate,fontSize:12,lineHeight:18,marginBottom:12,marginTop:5}, uploadPrivacy:{backgroundColor:C.amberPale,borderLeftColor:C.amber,borderLeftWidth:3,borderRadius:10,marginBottom:4,padding:10}, uploadPrivacyTitle:{color:'#9B660D',fontSize:8.5,fontWeight:'900',letterSpacing:.7}, uploadPrivacyCopy:{color:'#6E5524',fontSize:9.5,lineHeight:14,marginTop:4}, option:{alignItems:'center',borderBottomColor:'#EDF1F1',borderBottomWidth:1,flexDirection:'row',gap:12,paddingVertical:13}, optionIcon:{alignItems:'center',borderRadius:13,height:42,justifyContent:'center',width:42}, optionIconText:{color:C.navy,fontSize:20,fontWeight:'900'}, optionTitle:{color:C.ink,fontSize:14,fontWeight:'900'}, optionCopy:{color:C.slate,fontSize:10,marginTop:3}, optionArrow:{color:C.navy,fontSize:26},
});
